In [2]:
import numpy as np

In [1]:
# producto punto
l1 = [1, 2, 3]
l2 = [5, 4, 3]

product = 0
for i in range(len(l1)):
    product += l1[i] * l2[i]
    
product

22

In [3]:
array1 = np.array([1, 2, 3])
array2 = np.array([5, 4, 3])

array1.dot(array2)

22

In [4]:
np.dot(array1, array2)

22

In [5]:
mult = array1 * array2
mult

array([5, 8, 9])

In [6]:
sum(mult)

22

In [8]:
(array1 * array2).sum()

22

In [10]:
array1 @ array2

22

In [12]:
np.random.randn(10)

array([ 0.1064952 , -0.08043914, -1.31350076,  0.4156376 ,  2.64904088,
        0.11428753, -0.384326  , -2.00058338,  0.44698694, -0.08612944])

In [13]:
array1.shape

(3,)

In [15]:
array1.dtype

dtype('int32')

In [16]:
array1.size

3

In [18]:
# number of dimention
array1.ndim

1

In [19]:
# Item size in bytes
array1.itemsize

4

In [20]:
array1[0]

1

In [21]:
array1[0] = 20
array1

array([20,  2,  3])

In [22]:
array1 * array2

array([100,   8,   9])

In [23]:
array1 + 4

array([24,  6,  7])

In [24]:
array2 + np.array([6])

array([11, 10,  9])

In [25]:
array2 * 2

array([10,  8,  6])

In [26]:
np.sqrt(array2)

array([2.23606798, 2.        , 1.73205081])

In [27]:
np.log(array2)

array([1.60943791, 1.38629436, 1.09861229])