In [1]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

# CASTING
Para convertir tipos de datos de un array se usa el método `np.astype` del array, al cual se le pasa el tipo de dato deseado del array

In [2]:
arr.astype(np.int64)

array([[0, 1, 2],
       [3, 4, 5]], dtype=int64)

In [3]:
# para especificar un rango de datos bajo cierto criterio de salto
np.arange(-5, 5, 3, dtype=np.float64)

array([-5., -2.,  1.,  4.])

In [4]:
# para especificar el número de elementos en lugar del salto
np.linspace(1, 5, 11, dtype=np.float64)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [5]:
np.linspace(1, 5, 10, endpoint=False, dtype=np.float64)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

# RESHAPING DATA
Para cambiar las dimensiones de un array de NumPy se usa el método `np.reshape`

In [6]:
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [7]:
# las nuevas dimensiones deben contener todos los elementos del array
arr.reshape((3, 2))

array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)

In [8]:
np.reshape(arr, (1, 6))

array([[0., 1., 2., 3., 4., 5.]], dtype=float32)

In [9]:
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [10]:
# se puede aplanar un array para que sea de una sola dimensión
arr.flatten()

array([0., 1., 2., 3., 4., 5.], dtype=float32)

Es posible usar el valor especial de `-1` como máximo en una dimensión de la nueva forma. La dimensión con -1 tomará el valor necesario para permitir que la nueva forma contenga todos los elementos de la matriz.

In [11]:
arr2 = np.arange(8)
np.reshape(arr2, (-1, 1, 4))

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]]])

In [12]:
np.reshape(arr2, (-1, 2, 2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# cuando los datos deben ser dimensionados de cierta forma
# se puede usar newaxis para crear un eje nuevo en el array
a = np.arange(8)
# create new row axis
a[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [14]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [15]:
arr[:, np.newaxis]

array([[[0., 1., 2.]],

       [[3., 4., 5.]]], dtype=float32)

In [16]:
arr[np.newaxis, :]

array([[[0., 1., 2.],
        [3., 4., 5.]]], dtype=float32)

# TRANSPUESTA
Con el metodo `np.transpose` es posible determinar la transpuesta de la matriz

In [17]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr3 = arr3.reshape((2, 5))
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
# filas se convierten en columnas y columnas en filas
trans = np.transpose(arr3)
trans

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [20]:
arr3.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [21]:
trans.shape

(5, 2)

# ACCEDER A ELEMENTOS DEL ARRAY
Se usa la notación de corchetes de la misma forma que con listas

In [22]:
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [23]:
# si es una matriz, se obtiene como primer elemento un array
arr[0]

array([0., 1., 2.], dtype=float32)

In [24]:
# si es un array, se obtiene un elemento como en listas de Python
np.arange(-1, 5)[2]

1

# SLICING
Dado que los arrays pueden ser de multiples dimensiones, se debe especificar un segmento para cada dimension de la matriz
> `[rows, columns]`

In [25]:
mult_arr = np.linspace(1, 12, 12, dtype=np.int64)
mult_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [26]:
matrix = mult_arr.reshape((3, 4))
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int64)

In [27]:
# obtener [[2, 3], [6, 7]]
# Obtener una submatriz de las primeras dos filas y de las columnas 1 y 2
matrix[1:3,3]

array([ 8, 12], dtype=int64)

In [28]:
# Usar slicing trae un subarray del mismo orden que el original
sub_matrix = matrix[:2, 1:3]
sub_matrix

array([[2, 3],
       [6, 7]], dtype=int64)

In [29]:
# primera fila, segunda columna
matrix[0, 1]

2

In [30]:
# modificar un subarray altera la matriz principal
matrix[1, 2] = 10
matrix[1, 3] = 10

In [31]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6, 10, 10],
       [ 9, 10, 11, 12]], dtype=int64)

In [32]:
sub_matrix

array([[ 2,  3],
       [ 6, 10]], dtype=int64)

In [33]:
sub_matrix[0] = np.array([5, 6])

In [34]:
sub_matrix

array([[ 5,  6],
       [ 6, 10]], dtype=int64)

In [35]:
matrix

array([[ 1,  5,  6,  4],
       [ 5,  6, 10, 10],
       [ 9, 10, 11, 12]], dtype=int64)

In [36]:
matrix[1:]

array([[ 5,  6, 10, 10],
       [ 9, 10, 11, 12]], dtype=int64)

In [37]:
matrix[:, -1]

array([ 4, 10, 12], dtype=int64)

In [38]:
matrix[:,1:]

array([[ 5,  6,  4],
       [ 6, 10, 10],
       [10, 11, 12]], dtype=int64)

In [39]:
matrix[0:1, 1:]

array([[5, 6, 4]], dtype=int64)

In [40]:
matrix[0,1:]

array([5, 6, 4], dtype=int64)

## Integer Slicing
Usar un solo integer en la fila o la columna produce un array de orden inferior

In [41]:
matrix[1]

array([ 5,  6, 10, 10], dtype=int64)

In [42]:
# obtener filas
matrix[1, :]

array([ 5,  6, 10, 10], dtype=int64)

In [43]:
matrix[1:2, :]

array([[ 5,  6, 10, 10]], dtype=int64)

In [44]:
matrix[1:2, :].shape

(1, 4)

In [45]:
# obtener la última columna
matrix[:, 2]

array([ 6, 10, 11], dtype=int64)

In [46]:
matrix[:, 3:]

array([[ 4],
       [10],
       [12]], dtype=int64)

In [47]:
matrix[-1, -1]

12

# BOOLEAN INDEX
Al aplicar una condición sobre un array, obtengo el mismo array pero con valores booleanos. Si ese array compuesto por booleanos se usa como indice, se obtiene un array de primera dimensión con todos los datos que cumplen con la condición.
> Para obtener un array con las dimensiones iniciales, se usa `np.where`, pasando un valor default para aquellos valores que no cumplen con la condición

In [48]:
bool_index = matrix > 6
bool_index 

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [49]:
# Devuelve un array 1D
matrix[bool_index]

array([10, 10,  9, 10, 11, 12], dtype=int64)

In [50]:
np.where(matrix > 6, matrix, 0)

array([[ 0,  0,  0,  0],
       [ 0,  0, 10, 10],
       [ 9, 10, 11, 12]], dtype=int64)

In [51]:
np.any(matrix > 6)

True

In [52]:
np.all(matrix>6)

False

In [53]:
matrix[~(matrix > 6)]

array([1, 5, 6, 4, 5, 6], dtype=int64)

In [54]:
np.any(matrix > 6, axis=1)

array([False,  True,  True])

# FANCY INDEXING
Se usa para acceder a multiples elementos pasando listas de integers

In [55]:
array = np.arange(-1, 8)
array

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [56]:
array[[1, 2, 4]]

array([0, 1, 3])

In [57]:
# para obtener los indices que cumplen cierta condición
# se usa el método argwhere
even_indexes = np.argwhere(array % 2 == 0)
even_indexes

array([[1],
       [3],
       [5],
       [7]], dtype=int64)

In [58]:
even_indexes = even_indexes.flatten()
even_indexes

array([1, 3, 5, 7], dtype=int64)

In [59]:
# obtengo todos los pares
array[even_indexes]

array([0, 2, 4, 6])

In [60]:
# con matrices
matrix

array([[ 1,  5,  6,  4],
       [ 5,  6, 10, 10],
       [ 9, 10, 11, 12]], dtype=int64)

In [61]:
matrix[[0, 1, 1], [1, 2, 0]]

array([ 5, 10,  5], dtype=int64)

In [62]:
# es lo mismo que
print(np.array([matrix[0, 1], matrix[1, 2], matrix[1, 0]]))

[ 5 10  5]


In [63]:
# reusar el mismo elemento
matrix[[0, 0], [1, 1]]

array([5, 5], dtype=int64)

In [64]:
np.array([matrix[0, 1], matrix[0, 1]])

array([5, 5], dtype=int64)

In [65]:
np.array([matrix[0, 1], matrix[0, 1]]) == matrix[[0, 0], [1, 1]]

array([ True,  True])

In [66]:
# alterar un elemento de cada fila
new_matrix = np.arange(1, 13).reshape((4, 3))
new_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
b = np.array([0, 2, 0, 1])

In [68]:
new_matrix[np.arange(4), b]

array([ 1,  6,  7, 11])

In [69]:
# alterar esos elementos sumandoles 15
new_matrix[np.arange(4), b] += 15

In [70]:
new_matrix

array([[16,  2,  3],
       [ 4,  5, 21],
       [22,  8,  9],
       [10, 26, 12]])

# CONCATENATION
Para concatenar dos arrays, se usa la función `np.concatenate`, pasando una tupla con todos los arrays que se desean concatenar
- Concatenar todos los arrays en forma 1D con `axis=None`
- Concatenar agregando una fila con `axis=0`
- Concatenar una columna con `axis=1`
> Los arrays pasados al método deben tener la misma dimensión

In [71]:
arr = np.arange(6)
dec = np.arange(8)
np.concatenate((arr, dec, np.linspace(1, 5, 5)))

array([0., 1., 2., 3., 4., 5., 0., 1., 2., 3., 4., 5., 6., 7., 1., 2., 3.,
       4., 5.])

In [72]:
matrix

array([[ 1,  5,  6,  4],
       [ 5,  6, 10, 10],
       [ 9, 10, 11, 12]], dtype=int64)

In [73]:
np.concatenate((matrix, np.arange(4)), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [74]:
np.concatenate((matrix, np.arange(4).reshape(1, 4)), axis=0)

array([[ 1,  5,  6,  4],
       [ 5,  6, 10, 10],
       [ 9, 10, 11, 12],
       [ 0,  1,  2,  3]], dtype=int64)

In [75]:
np.concatenate((matrix, np.arange(3).reshape(3, 1)), axis=1)

array([[ 1,  5,  6,  4,  0],
       [ 5,  6, 10, 10,  1],
       [ 9, 10, 11, 12,  2]], dtype=int64)

In [76]:
np.arange(3).reshape(1, 3).T

array([[0],
       [1],
       [2]])

In [77]:
# append
array

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [78]:
np.append(array, 8)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [79]:
np.insert(array, 3, 7)

array([-1,  0,  1,  7,  2,  3,  4,  5,  6,  7])

In [80]:
np.insert(array, [0, -1, 5], [2, 3, 4])

array([ 2, -1,  0,  1,  2,  3,  4,  4,  5,  6,  3,  7])

In [81]:
# apilar horizontalmente
np.hstack((np.arange(5), np.linspace(0, 4, 5)))

array([0., 1., 2., 3., 4., 0., 1., 2., 3., 4.])

In [82]:
m1 = np.array([
    [1, 2],
    [3, 4]
])

m2 = np.array([
    [1, 2],
    [3, 4]
])

np.hstack((m1, m2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [83]:
# apilar verticalmente
np.vstack((np.arange(4), np.arange(4)))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [84]:
np.vstack((m1, m2))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

# BROADCASTING
Funcionalidad de NumPy que permite realizar operaciones entre arrays de diferentes dimensiones
> Frecuentemente se tiene un array de menor dimensión a otro, y se requiere que este sea utilizado para realizar multiples operaciones en el array de mayor dimensión

In [85]:
matrix

array([[ 1,  5,  6,  4],
       [ 5,  6, 10, 10],
       [ 9, 10, 11, 12]], dtype=int64)

In [86]:
matrix + np.arange(4)

array([[ 1,  6,  8,  7],
       [ 5,  7, 12, 13],
       [ 9, 11, 13, 15]], dtype=int64)

# RULES
* If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
* The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
* The arrays can be broadcast together if they are compatible in all dimensions.
* After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
* In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
> Funciones que permiten [usar BroadCasting](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs). Also [Numpy Documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [87]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

In [88]:
np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [89]:
x = np.array([[1,2,3], [4,5,6]])
x + v

array([[2, 4, 6],
       [5, 7, 9]])

In [90]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [91]:
x + np.reshape(w, (2, 1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [92]:
x * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

# MÁS FUNCIONES

In [93]:
# Esto es particularmente útil para evaluar funciones de múltiples dimensiones en una cuadrícula regular
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [94]:
np.indices((6,5))

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [95]:
# sum
a = np.arange(5)
b = np.arange(5, 10)
c = np.vstack((a, b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
# default = None
c.sum()

45

In [97]:
c.sum(axis=None)

45

In [98]:
# suma de columnas
c.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [99]:
c.sum(axis=1)

array([10, 35])

In [100]:
c.mean(axis=None)

4.5

In [101]:
c.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [102]:
c.mean(axis=1)

array([2., 7.])

In [103]:
#std, var, min, max, median

#For a more comprehensive list of statistical functions (e.g. calculating percentiles, creating histograms, etc.), check out the NumPy statistics page.

In [104]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
np.tile(c, (4, 1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
np.tile(c, (2, 2))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [107]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100,
                               size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
5
array([[15, 75],
       [12, 78]])


In [108]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


# MORE SLICING
![array](array.png)

In [109]:
final_matrix = np.arange(1, 31).reshape(6, 5)
final_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [110]:
submatrix_1 = final_matrix[2:4, 0:2]
submatrix_1

array([[11, 12],
       [16, 17]])

In [113]:
vector = final_matrix[np.arange(4), np.arange(1, 5)]
vector

array([ 2,  8, 14, 20])

In [124]:
final_matrix[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [125]:
# crear el siguiente array
mat = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 9, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1],
])

In [126]:
ones = np.ones((5, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [127]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [128]:
zeros[1, 1] = 9
zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [156]:
ones[1:-1, 1:-1] = zeros
ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

![array2](array2.png)

In [183]:
a = np.arange(6).reshape((1, 6))
a

array([[0, 1, 2, 3, 4, 5]])

In [184]:
np.concatenate((a, np.arange(10, 16)), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [185]:
for i in range(5):
    start = a[i, -1] + 5
    concat = np.arange(start, start + 6).reshape((1, 6))
    a = np.concatenate((a, concat), axis=0)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [188]:
yellow = a[0, 3:5]
yellow

array([3, 4])

In [190]:
red = a[:, 2]
red

array([ 2, 12, 22, 32, 42, 52])

In [192]:
green = a[[2, 4], ::2]
green

array([[20, 22, 24],
       [40, 42, 44]])

In [195]:
blue = a[-2:,-2:]
blue

array([[44, 45],
       [54, 55]])

In [197]:
green2 = a[2::2, ::2]
green2

array([[20, 22, 24],
       [40, 42, 44]])

![array3](array3.png)

In [198]:
red = a[[0, 2, -1], 2]
red

array([ 2, 22, 52])

In [200]:
orange = a[np.arange(5), np.arange(1, 6)]
orange

array([ 1, 12, 23, 34, 45])

In [203]:
blue = a[3:, [0, 2, -1]]
blue

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [204]:
mask = np.array([1, 0, 1, 0, 0, 1], dtype=np.bool)
orange2 = a[mask, 2]
orange2

array([ 2, 22, 52])

# CREACION DE ARREGLOS

In [133]:
A1 = [[1, 1, 1, 1],
 [1, 1, 1, 1],
 [1, 1, 1, 2],
 [1, 6, 1, 1]]

A2 = [[0., 0., 0., 0., 0.],
 [2., 0., 0., 0., 0.],
 [0., 3., 0., 0., 0.],
 [0., 0., 4., 0., 0.],
 [0., 0., 0., 5., 0.],
 [0., 0., 0., 0., 6.]]

A3 = [[4, 3, 4, 3, 4, 3],
 [2, 1, 2, 1, 2, 1],
 [4, 3, 4, 3, 4, 3],
 [2, 1, 2, 1, 2, 1]]

In [136]:
a1 = np.ones((4, 4), dtype=np.int32)
a1[[-2, -1], [-1, 1]] = [2, 6]
a1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 6, 1, 1]])

In [137]:
a2 = np.diag(np.arange(2, 7))
a2

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [140]:
a2 = np.vstack((np.zeros(5), a2))
a2

array([[0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 6.]])

In [145]:
np.diag(np.arange(2, 7), k=-1)[:, :-1].astype(np.float32)

array([[0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 6.]], dtype=float32)

In [206]:
a3 = np.flipud(np.arange(1, 5)).reshape((2, 2))
a3

array([[4, 3],
       [2, 1]])

In [207]:
a3 = np.tile(a3, (2, 3))
a3

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

# MATERIAL DE ESTUDIO
* https://numpy.org/doc/stable/reference/routines.math.html
* https://python-para-impacientes.blogspot.com/2019/10/primeros-pasos-con-numpy.html
* http://research.iac.es/sieinvens/python-course/source/numpy.html
* https://numpy.org/doc/stable/user/numpy-for-matlab-users.html
* https://numpy.org/doc/stable/
* https://docs.python.org/3/tutorial/
* https://cs231n.github.io/python-numpy-tutorial/#arrays
* https://docs.scipy.org/doc/scipy/reference/index.html
* https://numpy.org/doc/stable/reference/
* https://claudiovz.github.io/scipy-lecture-notes-ES/index.html
* https://numpy.org/doc/stable/reference/routines.array-creation.html
* https://numpy.org/doc/stable/reference/routines.linalg.html
* https://numpy.org/doc/stable/user/basics.broadcasting.html
* http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc